name: Run Robot Framework Tests

on:
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Instalar dependências
        run: |
          pip install robotframework
          pip install robotframework-seleniumlibrary
          pip install webdriver-manager

      - name: Configurar WebDriverManager e Rodar Testes
        run: |
          python -c "from webdriver_manager.chrome import ChromeDriverManager; ChromeDriverManager().install()"
          robot tests/